dist: trusty
sudo: required
language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc++-dev libc++abi-dev libopencv-dev libtbb-dev
  - mkdir build
  - pushd build

  - git clone https://github.com/google/googletest.git
  - pushd googletest
  - git checkout release-1.8.0
  - mkdir -p build/export
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=export && make && make install
  - popd
  - popd

  - git clone https://github.com/google/flatbuffers.git
  - pushd flatbuffers
  - git checkout v1.4.0
  - mkdir -p build/export
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=export && make && make install
  - popd
  - popd

  - git clone https://github.com/01org/tbb.git
  - pushd tbb
  - git checkout 2017_U3
  - make
  - popd

  - popd

script:
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DGTEST_ROOT=`pwd`/googletest/build/export -DCMAKE_PREFIX_PATH=`pwd`/flatbuffers/build/export -DCMAKE_CXX_FLAGS="-std=c++11 -I`pwd`/tbb/include" && make && make test
